//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections;
using EasySpreadsheet;


namespace DB
{
#if UNITY_EDITOR
	public static class UnityTypesParse
	{
		public static void Parse(ref UnityEngine.Vector2 v, string str)
		{
			string[] parts = str.Split('-');
			if (parts.Length > 0) { EsParser.TryParse(parts[0], out float _x_); v.x = _x_; }
			if (parts.Length > 1) { EsParser.TryParse(parts[1], out float _y_); v.y = _y_; }
		}

		public static void Parse(ref UnityEngine.Vector3 v, string str)
		{
			string[] parts = str.Split('-');
			if (parts.Length > 0) { EsParser.TryParse(parts[0], out float _x_); v.x = _x_; }
			if (parts.Length > 1) { EsParser.TryParse(parts[1], out float _y_); v.y = _y_; }
			if (parts.Length > 2) { EsParser.TryParse(parts[2], out float _z_); v.z = _z_; }
		}

		public static void Parse(ref UnityEngine.Rect v, string str)
		{
			string[] parts = str.Split('-');
			if (parts.Length > 0) { EsParser.TryParse(parts[0], out float _x_); v.x = _x_; }
			if (parts.Length > 1) { EsParser.TryParse(parts[1], out float _y_); v.y = _y_; }
			if (parts.Length > 2) { EsParser.TryParse(parts[2], out float _width_); v.width = _width_; }
			if (parts.Length > 3) { EsParser.TryParse(parts[3], out float _height_); v.height = _height_; }
		}

	}
#endif

	[Serializable]
	public partial class Int3
	{
		public int x;
		public int y;
		public int z;

#if UNITY_EDITOR
		public void Parse(string str)
		{
			string[] parts = str.Split('-');
			if (parts.Length > 0) EsParser.TryParse(parts[0], out x);
			if (parts.Length > 1) EsParser.TryParse(parts[1], out y);
			if (parts.Length > 2) EsParser.TryParse(parts[2], out z);
		}
#endif
	}

	[Serializable]
	public partial class Int2
	{
		public int x;
		public int y;

#if UNITY_EDITOR
		public void Parse(string str)
		{
			string[] parts = str.Split('-');
			if (parts.Length > 0) EsParser.TryParse(parts[0], out x);
			if (parts.Length > 1) EsParser.TryParse(parts[1], out y);
		}
#endif
	}

	[Serializable]
	public partial class Int4
	{
		public int x;
		public int y;
		public int z;
		public int w;

#if UNITY_EDITOR
		public void Parse(string str)
		{
			string[] parts = str.Split('-');
			if (parts.Length > 0) EsParser.TryParse(parts[0], out x);
			if (parts.Length > 1) EsParser.TryParse(parts[1], out y);
			if (parts.Length > 2) EsParser.TryParse(parts[2], out z);
			if (parts.Length > 3) EsParser.TryParse(parts[3], out w);
		}
#endif
	}


}