//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasySpreadsheet.
//     Runtime Version: 5.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasySpreadsheet;

namespace DB
{
	public sealed partial class DialogueTable : EsRowDataTable
	{
		[SerializeField]
		private List<Dialogue> _dataList = new List<Dialogue>();

		private Dictionary<int, Dialogue> _dataMap;
		public Dictionary<int, Dialogue> DataMap => _dataMap;
		public List<Dialogue> DataList => _dataList;

		public Dialogue Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
		public Dialogue this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

		protected override void OnDeserialized()
		{
			_dataMap = new Dictionary<int, Dialogue>(_dataList.Count);
			foreach (var data in _dataList)
			{
				_dataMap.Add(data.Id, data);
				(data as ISerializationCallbackReceiver).OnAfterDeserialize();
			}
			PostInit();
		}

		partial void PostInit();
	}
}

#if UNITY_EDITOR
namespace DB
{
	[UnityEditor.CustomEditor(typeof(DialogueTable))]
	public class DialogueInspector : EsAssetInspector
	{
	}
}
#endif